NetCore2RazorWebApp/webapphybridconn/Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace webapphybridconn.Pages
{
    public class AboutModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your application description page.";
        }
    }
}

NetCore2RazorWebApp/webapphybridconn/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace webapphybridconn.Pages
{
    public class ContactModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your contact page.";
        }
    }
}

NetCore2RazorWebApp/webapphybridconn/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace webapphybridconn.Pages
{
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

NetCore2RazorWebApp/webapphybridconn/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Net.Http;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;



namespace webapphybridconn.Pages
{
    public class IndexModel : PageModel
    {

        private static HttpClient client = new HttpClient();
        public string Records { get; set; }
        public List<RecordsViewModel> DRecords { get; set; }

        public string apiURL { get; set; }
        public string apiURL2 { get; set; }

        [FromForm]
        public string SerialNumber { get; set; }

        
        public async Task<IActionResult> OnPostSerialNumber()
        {
            
            
            apiURL = $"http://YOURAPPSERVICE.azurewebsites.net/api/values/devicerecords";

            apiURL2 = $"http://YOURAPPSERVICE.azurewebsites.net/api/values/logsn/" + SerialNumber;

            var opurl = new Uri(apiURL2);
            var res = await client.GetAsync(opurl);
            string textResult = await res.Content.ReadAsStringAsync();
            //ViewData["Message"] = textResult;
            //Records = textResult;

            ProcessRecords();
            Records = textResult;
            apiURL = apiURL2;

            return Page();
        }

        public IActionResult OnGet()
        {

            //List<RecordsViewModel> objList = GetRecords();

            ProcessRecords();

            //Task<string> pr = Task.Run<string>(async () => await PullRecords());
            //Records = pr.Result;
            //DRecords = new List<RecordsViewModel>();

            //if (Records.StartsWith("Error:") == false)
            //{
            //    JArray jsonVal = JArray.Parse(Records) as JArray;
            //    //dynamic CRecords = jsonVal;

            //    foreach (JObject CRecord in jsonVal)
            //    {
            //        RecordsViewModel temp = CRecord.ToObject<RecordsViewModel>();
            //        DRecords.Add(temp);
            //    }
            //}

            return Page();
        }

        private void ProcessRecords()
        {
            Task<string> pr = Task.Run<string>(async () => await PullRecords());
            Records = pr.Result;
            DRecords = new List<RecordsViewModel>();

            if (Records.StartsWith("Error:") == false)
            {
                JArray jsonVal = JArray.Parse(Records) as JArray;
                //dynamic CRecords = jsonVal;

                foreach (JObject CRecord in jsonVal)
                {
                    RecordsViewModel temp = CRecord.ToObject<RecordsViewModel>();
                    DRecords.Add(temp);
                }
            }

        }

        private async System.Threading.Tasks.Task<string> PullRecords()
        {
            apiURL = $"http://YOURAPPSERVICE.azurewebsites.net/api/values/devicerecords";
       
#if DEBUG
            //apiURL = $"http://localhost:7071/api/PullRecords";
#endif
            try
            {
                string response = await client.GetStringAsync(apiURL);
                return response as string;
            }
            catch (System.Exception ex)
            {
                return ("Error: " + ex.Message) as string;
            }
        }
    }

    public class RecordsViewModel
    {
        public string SerialNumber { set; get; }
        public string Comments { set; get; }
        public string ActivationDate { set; get; }
        public string SentTime { set; get; }

    }
}

NetCore2RazorWebApp/webapphybridconn/Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<p>Use this area to provide additional information.</p>

NetCore2RazorWebApp/webapphybridconn/Pages/Contact.cshtml
@page
@model ContactModel
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

NetCore2RazorWebApp/webapphybridconn/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}


<h4>API URL:  @Model.apiURL</h4>
<br />
<h3>Response Body:</h3>

@Model.Records

<hr />

<p />
<h3>Device Records</h3>
<table id="t01">

    <tr>
        <th>Serial Number</th>
        <th>Activation Date</th>
        <th>Comments</th>
        <th>SentTime</th>
    </tr>
    @foreach (RecordsViewModel record in Model.DRecords)
    {
        <tr>
            <td>@record.SerialNumber</td>
            <td>@record.ActivationDate</td>
            <td>@record.Comments</td>
            <td>@record.SentTime</td>

        </tr>
    }
</table>
<br />

<form asp-controller="Index" method="post">
    Serial Number:
    <input asp-for="SerialNumber" />
    <input type="submit" asp-page-handler="serialnumber" value="Update Activation Date" />
    <br>
</form>
<form asp-controller="Index" method="get">
    <input type="submit" style="float:right" name="btnReload" asp-page-handler="" value="Reload Data">
</form>
<br />



<style>
    table#t01 {
        width: 100%;
        background-color: #f1f1c1;
    }

        table#t01 tr:nth-child(even) {
            background-color: #eee;
        }

        table#t01 tr:nth-child(odd) {
            background-color: #fff;
        }

        table#t01 th {
            color: white;
            background-color: blue;
        }

    table, th, td {
        border: 1px solid black;
    }

    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
    }

    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
    }

    th, td {
        padding: 15px;
    }
</style>

@*<div class="row">
        <div class="col-md-3">
            <h2>Application uses</h2>
            <ul>
                <li>Sample pages using ASP.NET Core Razor Pages</li>
                <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
            </ul>
        </div>
        <div class="col-md-3">
            <h2>How to</h2>
            <ul>
                <li><a href="https://go.microsoft.com/fwlink/?linkid=852130">Working with Razor Pages.</a></li>
            </ul>
        </div>
        <div class="col-md-3">
            <h2>Overview</h2>
            <ul>
                <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            </ul>
        </div>
        <div class="col-md-3">
            <h2>Run &amp; Deploy</h2>
            <ul>
                <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            </ul>
        </div>
    </div>*@

NetCore2RazorWebApp/webapphybridconn/Pages/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - webapphybridconn</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-page="/Index" class="navbar-brand">webapphybridconn</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-page="/Index">Home</a></li>
                    <li><a asp-page="/About">About</a></li>
                    <li><a asp-page="/Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - webapphybridconn</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>